package br.com.receitasegura.api.model.enumeration;

public enum PermissaoDeAcesso {

	MEDICO_INCLUIR, MEDICO_EDITAR, MEDICO_REMOVER, MEDICO_RELATORIO, PACIENTE_INCLUIR, PACIENTE_EDITAR,
	PACIENTE_REMOVER, PACIENTE_RELATORIO, CONSELHO_INCLUIR, CONSELHO_EDITAR, CONSELHO_REMOVER, CONSELHO_RELATORIO,
	USUARIO_INCLUIR, USUARIO_EDITAR, USUARIO_REMOVER, USUARIO_RELATORIO, ESPECIALIDADE_INCLUIR, ESPECIALIDADE_EDITAR,
	ESPECIALIDADE_REMOVER, ESPECIALIDADE_RELATORIO, DOCUMENTO_INCLUIR, DOCUMENTO_EDITAR, DOCUMENTO_REMOVER,
	DOCUMENTO_RELATORIO

}
